CREATE TABLE public.activity
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    elevation real,
    hearthrate real,
    latitude real,
    longitude real,
    timezone character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT activity_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.activity
    OWNER to postgres;

CREATE TABLE public.athlete
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    easyhearthmax real,
    easyhearthmin real,
    hearthmax real,
    idathlete bigint,
    intervalhearthmax real,
    intervalhearthmin real,
    marathonhearthmax real,
    marathonhearthmin real,
    mass real,
    name character varying(255) COLLATE pg_catalog."default",
    repetitionhearthmax real,
    repetitionhearthmin real,
    surname character varying(255) COLLATE pg_catalog."default",
    thresholdhearthmax real,
    thresholdhearthmin real,
    CONSTRAINT athlete_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.athlete
    OWNER to postgres;

CREATE TABLE public.externalcondition
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    humidity real,
    idathlete bigint,
    idpoweractivity bigint,
    pressureatm real,
    speedwind real,
    temperature real,
    CONSTRAINT externalcondition_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.externalcondition
    OWNER to postgres;


CREATE TABLE public.poweractivity
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date character varying(255) COLLATE pg_catalog."default",
    distance real,
    hearthrate real,
    idathlete bigint,
    idpoweractivity bigint,
    pace real,
    power real,
    speed real,
    "time" character varying(255) COLLATE pg_catalog."default",
    timezone real,
    CONSTRAINT poweractivity_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.poweractivity
    OWNER to postgres;


CREATE TABLE public.prediction
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    idathlete bigint,
    idpoweractivity bigint,
    paceeasy character varying(255) COLLATE pg_catalog."default",
    paceforhalfmarathon character varying(255) COLLATE pg_catalog."default",
    pacehard character varying(255) COLLATE pg_catalog."default",
    pacemarathon character varying(255) COLLATE pg_catalog."default",
    pacemax character varying(255) COLLATE pg_catalog."default",
    pacemin character varying(255) COLLATE pg_catalog."default",
    paceoptimal character varying(255) COLLATE pg_catalog."default",
    pacefortenkm character varying(255) COLLATE pg_catalog."default",
    pacethreshold character varying(255) COLLATE pg_catalog."default",
    poweroptimal real,
    speedoptimal real,
    timeforhalfmarathon character varying(255) COLLATE pg_catalog."default",
    timeformarathon character varying(255) COLLATE pg_catalog."default",
    timefortenkm character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT prediction_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.prediction
    OWNER to postgres;

CREATE TABLE public.pressuresaturation
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    pressure real,
    temperature real,
    CONSTRAINT pressuresaturation_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.pressuresaturation
    OWNER to postgres;


CREATE TABLE public.statisticsactivity
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date character varying(255) COLLATE pg_catalog."default",
    deltafirstquartil real,
    deltathirdquartil real,
    deviation real,
    idathlete bigint,
    idpoweractivity bigint,
    nbrofeasy integer,
    nbrofinterval integer,
    nbrofmarathon integer,
    nbrofrepetition integer,
    nbrofthreshold integer,
    poweraverage real,
    powerfirstquartil real,
    powermedian real,
    powerscore real,
    powerthirdquartil real,
    CONSTRAINT statisticsactivity_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.statisticsactivity
    OWNER to postgres;

INSERT INTO "pressuresaturation" (id, temperature, pressure) VALUES
(01,-20,103),
(02,-18,150),
(03,-15,190),
(04,-12,240),
(05,-10,260),
(06,-9,300),
(07,-7,370),
(08,-4,460),
(09,-1,560),
(10,0,611),
(11,2,706),
(12,4,813),
(13,6,935),
(14,8,1073),
(15,10,1228),
(16,11,1312),
(17,12,1402),
(18,13,1497),
(19,14,1598),
(20,15,1705),
(21,16,1818),
(22,17,1937),
(23,18,2063),
(24,19,2197),
(25,20,2338),
(26,21,2487),
(27,22,2643),
(28,23,2809),
(29,24,2983),
(30,25,3167),
(31,26,3360),
(32,27,3564),
(33,28,3780),
(34,29,4005),
(35,30,4243),
(36,31,4492),
(37,32,4755),
(38,33,5030),
(39,34,5319),
(40,35,5623),
(41,36,5941),
(42,37,6275),
(43,38,6625),
(44,39,6992),
(45,40,7375),
(46,41,7778),
(47,42,8199),
(48,43,8639),
(49,44,9101),
(50,45,9583),
(51,46,10086),
(52,47,10612),
(53,48,11160),
(54,49,11735),
(55,50,12334);

